name: Publish Guardrails Hub Types

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12.x

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip;
        pip install twine;
        pip install build;
      continue-on-error: false

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install Node Dependencies
      run: |
        npm ci;
      continue-on-error: false
    
    - name: Create OpenAPI Spec Stub
      run: |
        npm run openapi-gen;
      continue-on-error: false

    - name: Build Typescript Module from OpenApi Spec
      run: |
        chmod +x ./ts-build.sh;
        bash ./ts-build.sh;
      continue-on-error: false

    - name: Build Python Libary from OpenApi Spec
      run: |
        chmod +x ./py-build.sh;
        bash ./py-build.sh;
      continue-on-error: false

    - name: Publish to NPM
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: |
        cd resources/ts
        npm publish
        cd ../..
      continue-on-error: false

    - name: Upload to PyPI
      env:
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        cd ./resources/py;
        python -m build;
        twine upload dist/* -u __token__ -p $PYPI_PASSWORD;
        cd ../..